// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using express_website.Models;

#nullable disable

namespace express_website.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250716092349_AddBlogTable")]
    partial class AddBlogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("express_website.Models.AlanClass", b =>
                {
                    b.Property<int>("AlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlanId"));

                    b.Property<int?>("AitOlduguElemanModeliElemanModeliId")
                        .HasColumnType("int");

                    b.Property<string>("AlanAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.HasKey("AlanId");

                    b.HasIndex("AitOlduguElemanModeliElemanModeliId");

                    b.ToTable("Alan");
                });

            modelBuilder.Entity("express_website.Models.AltBaslikClass", b =>
                {
                    b.Property<int>("AltBaslikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AltBaslikId"));

                    b.Property<int?>("AitOlduguBaslikBaslikId")
                        .HasColumnType("int");

                    b.Property<string>("AltBaslikAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaslikId")
                        .HasColumnType("int");

                    b.HasKey("AltBaslikId");

                    b.HasIndex("AitOlduguBaslikBaslikId");

                    b.ToTable("AltBaslik");
                });

            modelBuilder.Entity("express_website.Models.BaslikClass", b =>
                {
                    b.Property<int>("BaslikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaslikId"));

                    b.Property<string>("BaslikAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KategoriClassKategoriId")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.HasKey("BaslikId");

                    b.HasIndex("KategoriClassKategoriId");

                    b.ToTable("Baslik");
                });

            modelBuilder.Entity("express_website.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("express_website.Models.ElemanClass", b =>
                {
                    b.Property<int>("ElemanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElemanId"));

                    b.Property<int?>("AitOlduguAltBaslikAltBaslikId")
                        .HasColumnType("int");

                    b.Property<int>("AltBaslikId")
                        .HasColumnType("int");

                    b.Property<string>("ElemanAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElemanMetin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElemanId");

                    b.HasIndex("AitOlduguAltBaslikAltBaslikId");

                    b.ToTable("Eleman");
                });

            modelBuilder.Entity("express_website.Models.ElemanModeliClass", b =>
                {
                    b.Property<int>("ElemanModeliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ElemanModeliId"));

                    b.Property<int?>("AitOlduguElemanElemanId")
                        .HasColumnType("int");

                    b.Property<int>("ElemanId")
                        .HasColumnType("int");

                    b.Property<string>("ElemanModeliAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FiyatBilgisi1")
                        .HasColumnType("int");

                    b.Property<int?>("FiyatBilgisi2")
                        .HasColumnType("int");

                    b.HasKey("ElemanModeliId");

                    b.HasIndex("AitOlduguElemanElemanId");

                    b.ToTable("ElemanModeli");
                });

            modelBuilder.Entity("express_website.Models.HakkimizdaClass", b =>
                {
                    b.Property<int>("HakkimizdaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HakkimizdaId"));

                    b.Property<string>("HakkimizdaMetin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HakkimizdaId");

                    b.ToTable("Hakkimizda");
                });

            modelBuilder.Entity("express_website.Models.HucreClass", b =>
                {
                    b.Property<int>("HucreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HucreId"));

                    b.Property<int?>("AitOlduguAlanAlanId")
                        .HasColumnType("int");

                    b.Property<int>("AlanId")
                        .HasColumnType("int");

                    b.Property<string>("HucreMetin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HucreId");

                    b.HasIndex("AitOlduguAlanAlanId");

                    b.ToTable("Hucre");
                });

            modelBuilder.Entity("express_website.Models.KategoriClass", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategoriMetin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategori");
                });

            modelBuilder.Entity("express_website.Models.ProjeClass", b =>
                {
                    b.Property<int>("ProjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjeId"));

                    b.Property<string>("ProjeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProjeGorsel")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ProjeId");

                    b.ToTable("Proje");
                });

            modelBuilder.Entity("express_website.Models.ReferansClass", b =>
                {
                    b.Property<int>("ReferansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferansId"));

                    b.Property<byte[]>("ReferansGorsel")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ReferansId");

                    b.ToTable("Referans");
                });

            modelBuilder.Entity("express_website.Models.AlanClass", b =>
                {
                    b.HasOne("express_website.Models.ElemanModeliClass", "AitOlduguElemanModeli")
                        .WithMany("AlanListe")
                        .HasForeignKey("AitOlduguElemanModeliElemanModeliId");

                    b.Navigation("AitOlduguElemanModeli");
                });

            modelBuilder.Entity("express_website.Models.AltBaslikClass", b =>
                {
                    b.HasOne("express_website.Models.BaslikClass", "AitOlduguBaslik")
                        .WithMany("AltBaslikListe")
                        .HasForeignKey("AitOlduguBaslikBaslikId");

                    b.Navigation("AitOlduguBaslik");
                });

            modelBuilder.Entity("express_website.Models.BaslikClass", b =>
                {
                    b.HasOne("express_website.Models.KategoriClass", "KategoriClass")
                        .WithMany("BaslikListe")
                        .HasForeignKey("KategoriClassKategoriId");

                    b.Navigation("KategoriClass");
                });

            modelBuilder.Entity("express_website.Models.ElemanClass", b =>
                {
                    b.HasOne("express_website.Models.AltBaslikClass", "AitOlduguAltBaslik")
                        .WithMany("ElemanListe")
                        .HasForeignKey("AitOlduguAltBaslikAltBaslikId");

                    b.Navigation("AitOlduguAltBaslik");
                });

            modelBuilder.Entity("express_website.Models.ElemanModeliClass", b =>
                {
                    b.HasOne("express_website.Models.ElemanClass", "AitOlduguEleman")
                        .WithMany("ElemanModeliListe")
                        .HasForeignKey("AitOlduguElemanElemanId");

                    b.Navigation("AitOlduguEleman");
                });

            modelBuilder.Entity("express_website.Models.HucreClass", b =>
                {
                    b.HasOne("express_website.Models.AlanClass", "AitOlduguAlan")
                        .WithMany("HucreListe")
                        .HasForeignKey("AitOlduguAlanAlanId");

                    b.Navigation("AitOlduguAlan");
                });

            modelBuilder.Entity("express_website.Models.AlanClass", b =>
                {
                    b.Navigation("HucreListe");
                });

            modelBuilder.Entity("express_website.Models.AltBaslikClass", b =>
                {
                    b.Navigation("ElemanListe");
                });

            modelBuilder.Entity("express_website.Models.BaslikClass", b =>
                {
                    b.Navigation("AltBaslikListe");
                });

            modelBuilder.Entity("express_website.Models.ElemanClass", b =>
                {
                    b.Navigation("ElemanModeliListe");
                });

            modelBuilder.Entity("express_website.Models.ElemanModeliClass", b =>
                {
                    b.Navigation("AlanListe");
                });

            modelBuilder.Entity("express_website.Models.KategoriClass", b =>
                {
                    b.Navigation("BaslikListe");
                });
#pragma warning restore 612, 618
        }
    }
}
